package com.example.generatorutil.dao;

import com.example.generatorutil.model.TbDisposalInfo;

public interface TbDisposalInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    int insert(TbDisposalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    int insertSelective(TbDisposalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    TbDisposalInfo selectByPrimaryKey(String appCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbDisposalInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_disposal_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbDisposalInfo record);
}